#+TITLE:       Debian/Ubuntu 环境下常用软件安装
#+AUTHOR:      Sean Wang
#+EMAIL:       sean@think.sean.org
#+DATE:        2016-01-07 Thu
#+URI:         /blog/%y/%m/%d/install-debian
#+KEYWORDS:    debian, linux
#+TAGS:        debian, linux
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:t toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: Install common software in Debian 

* Install software via =apt-get= command
** Change =/etc/apt/sources.list=
Take Ubuntu 16.04 as an example. First, change the =sources.list= file:
#+BEGIN_SRC conf
# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse
deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted universe multiverse

# 预发布软件源，不建议启用
# deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-proposed main restricted universe multiverse
# deb-src https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-proposed main restricted universe multiverse
#+END_SRC

Then, update after change the sources.list file:
#+BEGIN_SRC shell
sudo apt-get update
#+END_SRC

** Install packages
You can put a list of many packages in a file named =pkg_list.txt=:
#+BEGIN_SRC conf
vim
tmux
zsh
htop
#+END_SRC

Then, install them using the following command:
#+BEGIN_SRC shell
sudo apt-get install $(grep -vE "^\s*#" pkg_list.txt | tr "\n" " ")
#+END_SRC
* Install software from source code
** Emacs
1. Download Emacs from [[http://ftp.gnu.org/gnu/emacs/][http://ftp.gnu.org/gnu/emacs/]]
2. Install dependencies:
#+BEGIN_SRC shell
sudo apt-get build-dep emacs24
#+END_SRC
3. Building Emacs:
#+BEGIN_SRC shell
cd emacs-25.x
./configure
make
make install
#+END_SRC
4. Install Spacemacs:
#+BEGIN_SRC shell
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
#+END_SRC
** GNU Parallel
#+BEGIN_SRC shell
wget http://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2
#+END_SRC
** oh-my-zsh
#+BEGIN_SRC shell
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
chsh -s /usr/local/bin/zsh
#+END_SRC
** zathura
** Lua
downloading: [[http://www.lua.org/download.html][http://www.lua.org/download.html]]
* Install =.deb= packages directly
** Chrome
download standalone installation package from
[[http://www.google.cn/intl/zh-CN/chrome/browser/desktop/index.html][http://www.google.cn/intl/zh-CN/chrome/browser/desktop/index.html]]

#+BEGIN_SRC shell
sudo dpkg -i google-chrome-stable_current_amd64.deb
#+END_SRC
* Install Python modules
** Install =pip= first
#+BEGIN_SRC shell
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py
#+END_SRC
** Install common modules
Put all modules needed to install in a file named =requirements.txt=:
#+BEGIN_SRC conf 
h5py
ipython
pandas
scikit-learn
matplotlib
numpy
#+END_SRC

#+BEGIN_SRC shell
sudo -H pip install -r requirements.txt
#+END_SRC

** TODO Use =virtualenv=
* Install software from custom package
** TexLive
Download [[http://mirrors.6.tuna.tsinghua.edu.cn/CTAN/systems/texlive/Images/texlive.iso][texlive.iso]],
#+BEGIN_SRC shell
wget https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/Images/texlive.iso
#+END_SRC

Mount texlive.ios and install texlive:
#+BEGIN_SRC shell
mkdir ./temp
sudo mount texlive.iso ./temp
sudo ./temp/install.tl
#+END_SRC
* Install Window Manager
** i3
downloading: [[http://i3wm.org/downloads/][http://i3wm.org/downloads/]]

* Install fonts
* System config
** Keyboard
在 =/etc/default/keyboard= 文件中添加下面一行，交换 =Ctrl= 和 =CapsLock= 键：

#+BEGIN_QUOTE
XKBOPTIONS="ctrl:nocaps"
#+END_QUOTE


完整的 =/etc/default/keyboard= 文件如下:

#+BEGIN_QUOTE
# Check /usr/share/doc/keyboard-configuration/README.Debian for
# documentation on what to do after having modified this file.

# The following variables describe your keyboard and can have the same
# values as the XkbModel, XkbLayout, XkbVariant and XkbOptions options
# in /etc/X11/xorg.conf.

XKBMODEL="pc105"
# XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS="ctrl:nocaps"

# If you don't want to use the XKB layout on the console, you can
# specify an alternative keymap.  Make sure it will be accessible
# before /usr is mounted.
# KMAP=/etc/console-setup/defkeymap.kmap.gz
BACKSPACE="guess"
#+END_QUOTE
