#+TITLE:       Abstract Translation: NDSS 2015 CopperDroid 
#+AUTHOR:      Sean Wang
#+EMAIL:       spark@bjtu.edu.cn
#+DATE:        2017-03-14 Tue
#+URI:         /blog/%y/%m/%d/abstract-translation-ndss-2015-copperdroid
#+KEYWORDS:    translation, paper
#+TAGS:        translation
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: study of top papers

* 论文基本信息
- 作者 :: Tam, Kimberly, Salahuddin J. Khan, Aristide Fattori, and Lorenzo Cavallaro. 
- 标题 :: CopperDroid: Automatic Reconstruction of Android Malware Behaviors.
- 发表于 :: NDSS. 2015.

* 摘要翻译
#+BEGIN_QUOTE
Mobile devices and their application marketplaces drive the entire economy of
the today’s mobile landscape. 
#+END_QUOTE

移动设备和移动应用市场驱动了今天整个移动行业经济的发展。

#+BEGIN_QUOTE
Android platforms alone have produced staggering revenues, exceeding ﬁve billion
USD, which has attracted cybercriminals and increased malware in Android markets
at an alarming rate.
#+END_QUOTE

仅 Android 平台自身就创造了超过 50 亿美金的令人难以置信的收益。但这也吸引了网络
犯罪，Android 市场上恶意应用正在以令人担忧的速率快速增加。

- /staggering/, so great, shocking or surprising that it is difficult to believe
  令人难以相信的

#+BEGIN_QUOTE
To better understand this slew of threats, we present CopperDroid, an automatic
VMI-based dynamic analysis system to reconstruct the behaviors of Android
malware.
#+END_QUOTE

为了深入理解 Android 平台面临的恶意应用威胁，本文提出了 CopperDroid, 一种基于虚
拟机自省技术(VMI)的自动化动态分析系统，用来重建 Android 恶意应用的行为.

#+BEGIN_QUOTE
The novelty of CopperDroid lies in its agnostic approach to identify interesting
OS- and high-level Android-speciﬁc behaviors.
#+END_QUOTE

CopperDroid 的创新之处在于，他采用了一种（底层）不可知的方法来发现（恶意应用中）
值得关注的 OS 层行为和 Android 特有的高层行为。

#+BEGIN_QUOTE
It reconstructs these behaviors by observing and dissecting system calls and,
therefore, is resistant to the multitude of alterations the Android runtime is
subjected to over its life-cycle.
#+END_QUOTE

通过监视并剖析系统调用，CopperDroid 就能够重建这些行为。（由于系统调用在 Android
运行时之下），因此，在 CopperDroid 的整个生命周期中，即使 Android 运行时发生多种
变化，它都不受影响。

#+BEGIN_QUOTE
CopperDroid automatically and accurately reconstructs events of interest that
describe, not only well-known process-OS interactions (e.g., ﬁle and process
creation), but also complex intra- and inter-process communications (e.g., SMS
reception), whose semantics are typically contextualized through complex Android
objects.
#+END_QUOTE

CopperDroid 能自动并且准确地重建所关注的事件。这些事件不仅描述了常见的进程-操作
系统交互（例如，文件和进程的创建），而且描述了复杂的进程内部和进程间通信（例如，
SMS 接收）。一般来说，进程内和进程间通信事件的语义必须放在复杂的 Android 对象的上
下文环境中考虑。


#+BEGIN_QUOTE
Because CopperDroid’s reconstruction mechanisms are agnostic to the underlying
action invocation methods, it is able to capture actions initiated both from
Java and native code execution.
#+END_QUOTE

由于 CopperDroid 的重建机制不会被下层活动的调用方法所感知，所以无论从 Java 发起的还
是从本地代码中发起的行为，它都能捕获。

#+BEGIN_QUOTE
CopperDroid’s analysis generates detailed behavioral proﬁles that abstract a
large stream of low-level—often uninteresting—events into concise, high-level
semantics, which are well-suited to provide insightful behavioral traits and
open the possibility to further research directions.
#+END_QUOTE

CopperDroid 的分析能将大量底层的——往往很无趣的——事件抽象成简洁的、高层次的语义描
述，从而产生恶意应用的详细的行为特征轮廓。这种轮廓非常适合提供恶意应用的有洞察力
的行为特点，而且给未来的研究方向带来更多可能。

#+BEGIN_QUOTE
We carried out an extensive evaluation to assess the capabilities and
performance of CopperDroid on more than 2,900 Android malware samples.
#+END_QUOTE

我们在超过 2900 个 Android 恶意应用上作了大量测试，以评估 CopperDroid 的功能和性能。

#+BEGIN_QUOTE
Our experiments show that CopperDroid faithfully reconstructs OS- and
Android-speciﬁc behaviors.
#+END_QUOTE

实验表明，CopperDroid 能准确地重建 OS 层行为和 Android 特有行为。

#+BEGIN_QUOTE
Additionally, we demonstrate how CopperDroid can be leveraged to disclose
additional behaviors through the use of a simple, yet effective, app stimulation
technique.
#+END_QUOTE

另外，通过使用一种简单但有效的 app 模拟技术，我们展示了如何借助 CopperDroid 暴露应用
的更多行为。

#+BEGIN_QUOTE
Using this technique, we successfully triggered and disclosed additional
behaviors on more than 60% of the analyzed malware samples.
#+END_QUOTE

利用这种技术，在所分析的应用中，我们成功在 60% 以上的应用中触发并暴露了额外行为。

#+BEGIN_QUOTE
This qualitatively demonstrates the versatility of CopperDroid’s ability to
improve dynamic-based code coverage.
#+END_QUOTE

这定性地说明，CopperDroid 在提高动态分析代码覆盖率上也有一定作用。
