#+TITLE:       Word List 20170601
#+AUTHOR:      Sean Wang
#+EMAIL:       spark@bjtu.edu.cn
#+DATE:        2017-06-01 Thu
#+URI:         /blog/%y/%m/%d/word-list-20170601
#+KEYWORDS:    TE
#+TAGS:        TE
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

- /Schumpeter/ :: United States economist (born in Czechoslovakia)
- /eliminate/ :: 动词消除，剔除，根除(尤指不需要之物) To eliminate something, especially something you do not want or need, means to remove it completely.
- /plague/ :: 动词困扰；使烦恼；折磨 If you are plagued by unpleasant things, they continually cause you a lot of trouble or suffering.
- /witness/ :: 动词以…为证;…便是明证 You use witness to introduce an example of what you have just been talking about.
- /ambitious/ :: 能被表示程度的副词或介词词组修饰的形容词有雄心的；有抱负的；有野心的 Someone who is ambitious has a strong desire to be successful, rich, or powerful.
- /fraudster/ :: 可数名词诈骗犯;欺诈犯 A fraudster is someone who commits the crime of fraud.
- /contemporary/ :: 可数名词同时期的人;同时代的人 Someone's contemporary is a person who is or was alive at the same time as them.
- /reportedly/ :: 副词据说;据报道 If you say that something is reportedly true, you mean that someone has said that it is true, but you have no direct evidence of it.
- /divert/ :: 动词改变(资金、资源)的用途;转移 To divert money or resources means to cause them to be used for a different purpose.
- /wayward/ :: 能被表示程度的副词或介词词组修饰的形容词任性的;不易管教的;难以捉摸的 If you describe a person or their behaviour as wayward, you mean that they behave in a selfish, bad, or unpredictable way, and are difficult to control.
- /acute/ :: 能被表示程度的副词或介词词组修饰的形容词（情况）严重的；（感觉）强烈的 You can use acute to indicate that an undesirable situation or feeling is very severe or intense.
- /strain/ :: 动词使不堪承受;使紧张 To strain something means to make it do more than it is able to do.
- /bond/ :: 可数名词（情感的）纽带，契合，关系 A bond between people is a strong feeling of friendship, love, or shared beliefs and experiences that unites them.
- /loyalty/ :: 不可数名词忠诚；忠心；忠贞不渝 Loyalty is the quality of staying firm in your friendship or support for someone or something.
- /rife/ :: 能被表示程度的副词或介词词组修饰的形容词（通常指坏事）普遍的，盛行的，常见的，充斥的 If you say that something, usually something bad, is rife in a place or that the place is rife with it, you mean that it is very common.
- /harsh/ :: 能被表示程度的副词或介词词组修饰的形容词（言行）严厉的，无情的 Harsh actions or speech are unkind and show no understanding or sympathy.
- /liable/ :: 形容词（在法律上）有责任的，有义务的 If you are liable for something such as a debt, you are legally responsible for it.
- /imitator/ :: 可数名词模仿者;仿效者 An imitator is someone who copies what someone else does, or copies the way they speak or behave.
- /bribe/ :: 动词向…行贿 If one person bribes another, they give them a bribe.
- /incur/ :: 动词招致;带来;遭受 If you incur something unpleasant, it happens to you because of something you have done.
- /bid/ :: 动词投标；竞标；出价 If you bid for something that is being sold, you offer to pay a particular amount of money for it.
- /boycott/ :: 动词抵制；拒绝参加 If a country, group, or person boycotts a country, organization, or activity, they refuse to be involved with it in any way because they disapprove of it.
- /scam/ :: 可数名词(通常以诈财或逃税为目的的)诡计，阴谋，骗局 A scam is an illegal trick, usually with the purpose of getting money from people or avoiding paying tax.
- /telltale/ :: Something that is described as telltale gives away information, often about something bad that would otherwise not be noticed.
- /trickster/ :: 可数名词骗子;(常指)诈骗钱财的人 A trickster is a person who deceives or cheats people, often in order to get money from them.
- /flamboyant/ :: 能被表示程度的副词或介词词组修饰的形容词引人注目的;炫耀的;时髦的 If you say that someone or something is flamboyant, you mean that they are very noticeable, stylish, and exciting.
- /swishing/ :: The sound of fabric or fur moving in the air.
- /reptilian/ :: 形容词爬行的;爬行动物的 A reptilian creature is a reptile.
- /giveaway/ :: 单数名词暴露真相的事物 A giveaway is something that makes you realize the truth about a particular person or situation.
- /borderline/ :: between two different conditions, with the possibility of belonging to either one of them 两可的，临界的；所属不清的
- /psychopath/ :: 可数名词精神变态者；变态人格者 A psychopath is someone who has serious mental problems and who may act in a violent way without feeling sorry for what they have done.
- /conceal/ :: 动词掩盖;隐藏 If you conceal something, you cover it or hide it carefully.
- /misdemeanour/ :: 可数名词（美国等国家的）轻罪 In the United States and other countries where the legal system distinguishes between very serious crimes and less serious ones, a misdemeanour is a less serious crime.
- /derivative/ :: 可数名词派生物;衍生物 A derivative is something which has been developed or obtained from something else.
- /colleague/ :: 可数名词同事;同僚 Your colleagues are the people you work with, especially in a professional job.
- /inflate/ :: 动词夸张;夸大;吹嘘 If someone inflates the amount or effect of something, they say it is bigger, better, or more important than it really is, usually so that they can profit from it.
- /commission/ :: 动词正式委托;委托(做) If you commission something or commission someone to do something, you formally arrange for someone to do a piece of work for you.
- /rigorous/ :: 能被表示程度的副词或介词词组修饰的形容词(测试、系统或程序)严格的，严密的，缜密的 A test, system, or procedure that is rigorous is very thorough and strict.
- /lure/ :: 动词引诱；诱惑；哄骗 To lure someone means to trick them into a particular place or to trick them into doing something that they should not do.
- /renegade/ :: 形容词离经叛道的;叛逆的;变节的 Renegade is used to describe a member of a group or profession who behaves in a way that is opposed to the normal behaviour or beliefs of that group or profession.
- /harness/ :: 动词控制（情感）;利用（自然力）If you harness something such as an emotion or natural source of energy, you bring it under your control and use it.
- /accomplice/ :: 可数名词共犯;同谋;帮凶 Someone's accomplice is a person who helps them to commit a crime.
- /devastating/ :: 能被表示程度的副词或介词词组修饰的形容词毁灭性的;极具破坏力的 If you describe something as devastating, you are emphasizing that it is very harmful or damaging
- /praise/ :: 动词称赞；赞扬；表扬 If you praise someone or something, you express approval for their achievements or qualities.
- /bearer/ :: 可数名词送（口信等）的人；带信人 The bearer of something such as a message is the person who brings it to you.
- /whistleblower/ :: 可数名词告发者;检举者 A whistle-blower is someone who finds out that the organization they are working for is doing something immoral or illegal and tells the authorities or the public about it.
- /illicit/ :: 形容词非法的;违禁的;不正当的 An illicit activity or substance is not allowed by law or the social customs of a country.
- /incentive/ :: 可变名词刺激;激励;奖励 If something is an incentive to do something, it encourages you to do it.
- /dither/ :: 动词犹豫不决;踌躇 When someone dithers, they hesitate because they are unable to make a quick decision about something.
- /blather/ :: 动词喋喋不休；废话连篇；絮絮叨叨 If someone is blathering on about something, they are talking for a long time about something that you consider boring or unimportant.
- /tempest/ :: 可数名词风波;风暴 You can refer to a situation in which people are very angry or excited as a tempest
- /decisive/ :: 能被表示程度的副词或介词词组修饰的形容词果断的;决断的 If someone is decisive, they have or show an ability to make quick decisions in a difficult or complicated situation.
- /botched/ :: describes something, usually a job, that is done badly（尤指工作）一团糟的
- /deliberate/ :: 能被表示程度的副词或介词词组修饰的形容词故意的;蓄意的;早有计划的 If you do something that is deliberate, you planned or decided to do it beforehand, and so it happens on purpose rather than by chance.
- /culprit/ :: 可数名词罪犯;犯错的人 When you are talking about a crime or something wrong that has been done, you can refer to the person who did it as the culprit .
- /hired hand/ :: a person who is paid to work on a farm 农场雇工
- /abuse one's trust/ :: 辜负了某人的信任, 滥用某人的信任
- /at the moment/ :: right now; At this moment
- /temporary worker/ :: a worker (especially in an office) hired on a temporary
- /hit targets/ :: 命中目标
- /hold down/ :: 短语动词压制;限制 If you hold someone down, you keep them under control and do not allow them to have much freedom or power or many rights.
- /have a field day/ :: to have the chance to do something that you really enjoy, especially when it causes trouble for someone else; to get a lot of pleasure and enjoyment from doing something, used especially to describe getting enjoyment from criticizing someone, making fun of someone, etc.
- /run the risk of/ :: to do something that may result in (something bad or unpleasant happening)
- /be barred from/ :: 动词禁止；不准 If someone is barred from a place or from doing something, they are officially forbidden to go there or to do it.
- /be subjected to something/ :: 遭受某事
- /uncover internal scams/ :: 发现内部骗局
- /a timely guide/ :: 及时的，适时的指导
- /pluck up courage to do something/ :: to persuade yourself to do something that frightens you
- /larger than life/ :: someone who is larger-than-life has a very strong or lively personality that impresses people very much
- /cover for/ :: to protect someone from punishment, for example by telling a lie for them
- /put procedures in place/ :: 落实。。。程序
- /back channel/ :: a secret, unofficial, or irregular means of communication
- /tip-off/ :: 可数名词密报;密告 A tip-off is a piece of information or a warning that you give to someone, often privately or secretly.
- /half-hearted/ :: 能被表示程度的副词或介词词组修饰的形容词半心半意的;不热心的 If someone does something in a half-hearted way, they do it without any real effort, interest, or enthusiasm.
- /end up doing something/ :: 短语动词最终；结果；到头来 If you end up doing something or end up in a particular state, you do that thing or get into that state even though you did not originally intend to.
- /cover one's tracks/ :: to conceal traces in order to elude pursuers or escape detection
- /be up to something/ :: to be doing something, often something bad or illegal, usually secretly（通常指偷偷地）正在做（常指坏事或不法之事）
