#+TITLE:       Word List 20170303 (Genetically modified crops, Gene-policy transfer)
#+AUTHOR:      Sean Wang
#+EMAIL:       spark@bjtu.edu.cn
#+DATE:        2017-08-01 Tue
#+URI:         /blog/%y/%m/%d/word-list-20170303
#+KEYWORDS:    TE, English
#+TAGS:        TE
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: <TODO: insert your description here>

- /Genetically/ :: connected with GENES, 副词，基因的，遗传学的
- /relax/ :: to allow rules, laws, etc. to become less strict 放宽（限制等）
- /total ban/ :: total 此处意思是 complete, or as great as is possible
- /fierce/ :: involving very strong feelings such as determination, anger, or hate
- /recount/ :: to tell sb about sth, especially sth that you have experienced 讲述，叙述（亲身经历）
- /famine/ :: Famine is a situation in which large numbers of people have little or no food, and many of them die. 饥馑；饥荒
- /lean/ :: difficult and not producing much money, food, etc. 难以赚钱的；生产不出（食物等）的；贫乏的
- /Cultural Revolution/ :: 文革
- /hint at sth/ :: to suggest sth in an indirect way, 暗示；透露；示意
- /remedy/ :: a successful way of curing an illness or dealing with a problem or difficulty 疗法，治疗；补救（办法），纠正（办法）
- /commanding/ :: if you are in a commanding position or have a commanding lead, you are likely to win a race or competition 居领先位置的；遥遥领先的（指可能赢得赛跑或比赛）
- /yield/ :: to allow sb to win, have or take control of sth that has been yours until now 放弃；缴出
- /flabbergast/ :: to shock someone, usually by telling them something they were not expecting 使大吃一惊；使目瞪口呆
- /regulator/ :: someone who makes sure that a system operates properly or fairly,监管者，监管机构
- /hectare/ :: a unit of measurement of an area of land 公顷; 一万平方米
- /grow/ :: linking verb, to begin to have a particular quality or feeling over a period of time 逐渐变得；逐渐成为
- /conservative/ :: often not liking or trusting change, especially sudden change 保守的；守旧的
- /reliant/ :: ~ on/ upon sb/ sth needing sb/ sth in order to survive, be successful, etc. 依赖性的；依靠的
- /soyabeans/ :: the bean of an Asian plant from which oil and food containing a lot of protein are produced, 大豆
- /cultivation/ :: the preparation and use of land for growing plants or crops 耕种；种植；栽培
- /papaya/ :: a tropical (热带的) fruit with yellow and green skin, sweet orange or red flesh (果肉) and round black seeds 番木瓜；（俗称）木瓜
- /be reluctant to/ :: hesitating before doing sth because you do not want to do it or because you are not sure that it is the right thing to do 不情愿的；勉强的
- /staple/ :: a main product or part of something 主要产品，或某物的主要部分
- /maize/ :: 玉米
- /growing/ :: increasing in size, amount or degree 增加的；增长的；增强的
- /ease/ :: if something unpleasant eases, or if you ease it, it gradually improves or becomes less, 宽慰；减轻；缓解
- /go ahead/ :: If someone goes ahead with something, they begin to do it or make it, especially after planning, promising, or asking permission to do it. 着手；开始做
- /takeover/ :: an act of taking control of a company by buying most of its shares 收购；接收；接管
- /ChemChina/ :: 中国化工集团公司
- /acquisition/ :: a company, piece of land, etc. bought by sb, especially another company; the act of buying it 购置物；收购的公司；购置的产业；购置；收购
- /belated/ :: coming or happening late 迟来的；晚出现的
- /barn/ :: a large building on a farm in which hay (草料) (= dried grass) and grain are kept 谷仓，粮仓
- /relax the total ban/ :: 放宽全面禁令
- /went months without/ :: 几个月都没有
- /the commanding heights of/ :: 处于有利地位
- /a deal reached in February/ :: 达成的交易
- /said for the first time that/ :: 首次提出
